{% set name = "skll" %}
{% set version = "5.0.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/EducationalTestingService/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 2a0a01c00bc586cc8b5684dff0a85439e11e483cd1602d1669657ed44e99af08

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - compute_eval_from_predictions = skll.utils.commandline.compute_eval_from_predictions:main
    - filter_features = skll.utils.commandline.filter_features:main
    - generate_predictions = skll.utils.commandline.generate_predictions:main
    - join_features = skll.utils.commandline.join_features:main
    - plot_learning_curves = skll.utils.commandline.plot_learning_curves:main
    - print_model_weights = skll.utils.commandline.print_model_weights:main
    - run_experiment = skll.utils.commandline.run_experiment:main
    - skll_convert = skll.utils.commandline.skll_convert:main
    - summarize_results = skll.utils.commandline.summarize_results:main

requirements:
  host:
    - python >=3.10
    - pip
    - setuptools
  run:
    - python >=3.10
    - beautifulsoup4
    - joblib
    - numpy <2
    - pandas
    - ruamel.yaml
    - scikit-learn >=1.4.0,<1.5.0
    - scipy
    - seaborn
    - tabulate
    - typing_extensions
    - wandb

test:
  # Python imports
  imports:
    - skll

  commands:
    - compute_eval_from_predictions --help
    - filter_features --help
    - generate_predictions --help
    - join_features --help
    - plot_learning_curves --help
    - print_model_weights --help
    - run_experiment --help
    - skll_convert --help
    - summarize_results --help

about:
  home: http://github.com/EducationalTestingService/skll
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: SciKit-Learn Laboratory makes it easier to run machine learning experiments with scikit-learn.

extra:
  recipe-maintainers:
    - ngam
    - desilinguist
    - mulhod
    - Frost45
